language: python

python:
  - "3.6"

notifications:
  email:
    recipients:
      - $(git --no-pager show -s --format=\%ae)
    on_success: always # default: change
    on_failure: always # default: always

install:
  - sudo docker-compose up -d builder

script:
  - git --no-pager show -s --format=\%ae
  - sudo docker-compose run test