version: '2'

services:
  builder:
    build: .

  test:
    build: .
    command: python -m unittest app/test_Detector.py
    volumes:
      - .:/code

  app:
    build: .
    command: python app/app.py 0.0.0.0:5001
    volumes:
      - .:/code
    ports:
      - "5001:5001"
