version: '2'

services:
  test:
    build: .
    command: python app/manage.py test app
    volumes:
      - .:/code

  app:
    build: .
    command: python app/app.py 0.0.0.0:5000
    volumes:
      - .:/code
    ports:
      - "5000:5000"
